[package]
name = "chver"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chver"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
chrono = { version = "0.4", features = ["clock"] }
color-eyre = "0.6"
semver = "1.0"
toml_edit = "0.22"

[dev-dependencies]
insta = { version = "1.0", features = ["yaml"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
